// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjKH6vbpsTrDhqpsNT7AovPCPeaXIAqVA',
    appId: '1:263544271376:web:0a44c5c02eecaab949d095',
    messagingSenderId: '263544271376',
    projectId: 'medproject-7e535',
    authDomain: 'medproject-7e535.firebaseapp.com',
    storageBucket: 'medproject-7e535.appspot.com',
    measurementId: 'G-DHE4NYQ3TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIIFOsBmLBuEMdAo75gCiCY4v8opBIPgo',
    appId: '1:263544271376:android:3164c334521d4afd49d095',
    messagingSenderId: '263544271376',
    projectId: 'medproject-7e535',
    storageBucket: 'medproject-7e535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfX5R333rtNQD70RyVLn2Y0-RcVveYwJE',
    appId: '1:263544271376:ios:6f593c9102081a7949d095',
    messagingSenderId: '263544271376',
    projectId: 'medproject-7e535',
    storageBucket: 'medproject-7e535.appspot.com',
    iosBundleId: 'com.example.medg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfX5R333rtNQD70RyVLn2Y0-RcVveYwJE',
    appId: '1:263544271376:ios:6bd3968ac8dbb95a49d095',
    messagingSenderId: '263544271376',
    projectId: 'medproject-7e535',
    storageBucket: 'medproject-7e535.appspot.com',
    iosBundleId: 'com.example.medg.RunnerTests',
  );
}
